### ISSUE TITLE
[BUG] Database page list - Rename column

### ISSUE THREAD

**Issue by raffaelloferrari** [ercole-io/ercole-web#217]
**Describe the bug**
In page http://dev.ercole.io/databases I want change column name as:
Mem. --> Memory (GB)
DataFile --> Datafile size (GB)
Seg. --> Segment size (GB)
A --> Archivelog Mode 
D --> DR

In column Mem values I don't want to see TB.

In the left box sobstitute TB with GB

**Comment by cirelli94** [comment]
I reopen this because we need GB size instead of TB even in the left box, please:
![image](https://user-images.githubusercontent.com/1636493/92740905-6c805500-f37e-11ea-868d-5f90755d373b.png)
And in "Memory (GB)" column we have to hide the size, so remove GB and just let the value to be more consistent with other columns:
![image](https://user-images.githubusercontent.com/1636493/92741095-976aa900-f37e-11ea-809a-aa3cc395f354.png)

**Comment by raffaelloferrari** [comment]
@rcmaiolini plaease can tou rename this 
![image](https://user-images.githubusercontent.com/47225245/92749114-18796e80-f386-11ea-8242-d2724147acf7.png)
to
"High Availability"

**Comment by rcmaiolini** [comment]
Fatto

**Comment by raffaelloferrari** [comment]
Now I notice that we have to modify also Oracle page
